### ISSUE TITLE
CI condition for installing LLVM libc++ wrong

### ISSUE THREAD

**Issue by ahueck** [tudasc/TypeART#87]
Is:

```yaml
      - name: Install libc++
        if: matrix.libcxx
        run: sudo apt-get install --no-install-recommends libc++-10-dev libc++abi-10-dev

```

should be:
```yaml
      - name: Install libc++
        if: matrix.preset.libcxx
        run: sudo apt-get install --no-install-recommends libc++-10-dev libc++abi-10-dev

```
